# Generated by Django 3.0.6 on 2020-05-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.BooleanField()),
                ('group', models.CharField(choices=[('MOBILE', 'mobile'), ('COMPUTERS', 'computers'), ('LAPTOP', 'laptop'), ('ACC', 'accessories')], default='mobile', max_length=20)),
                ('img', models.ImageField(default='no_image.jpg', upload_to='product_image')),
            ],
        ),
    ]
