# Generated by Django 3.0.6 on 2020-05-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('COMPUTERS', 'computers'), ('MOBILE', 'mobile'), ('LAPTOP', 'laptop'), ('ACC', 'accessories')], default='mobile', max_length=20),
        ),
    ]
