# Generated by Django 3.0.6 on 2020-05-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200519_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('ACC', 'accessories'), ('COMPUTERS', 'computers'), ('LAPTOP', 'laptop'), ('MOBILE', 'mobile')], default='mobile', max_length=20),
        ),
    ]
