# Generated by Django 3.0.6 on 2020-05-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200519_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('MOBILE', 'mobile'), ('LAPTOP', 'laptop'), ('COMPUTERS', 'computers'), ('ACC', 'accessories')], default='mobile', max_length=20),
        ),
    ]
