# Generated by Django 3.0.6 on 2020-05-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200519_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('LAPTOP', 'laptop'), ('COMPUTERS', 'computers'), ('ACC', 'accessories'), ('MOBILE', 'mobile')], default='mobile', max_length=20),
        ),
    ]
